several small display issues

diff --git a/menu/prj/git/upl b/menu/prj/git/upl
--- a/menu/prj/git/upl
+++ b/menu/prj/git/upl
@@ -1,7 +1,7 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # ------------------------------------------------------------------------
 #
-# Copyright (c) 2014 by Simon Arjuna Erat (sea)  <erat.simon@gmail.com>
+# Copyright (c) 2014-2015 by Simon Arjuna Erat (sea)  <erat.simon@gmail.com>
 # All rights reserved.
 #
 # This program is free software: you can redistribute it and/or modify it
@@ -20,20 +20,23 @@
 # ------------------------------------------------------------------------
 #
 #	
-	script_version=0.1
+	. $HOME/.config/dev-scripts/dev-scripts.conf
+	. /usr/share/dev-scripts/*
+	
+	script_version=0.2
 #
 #	Title
 #
 	title="$OA_TITLE - GIT Handler - Upload repositry"
 	tui-title "$title ($script_version)"
-	[[ -f "$CONF_GIT" ]] || \
+	[ -f "$CONF_GIT" ] || \
 		(tui-wait 5s "Please take care to provide all required data...";ds setup)
 	source "$CONF_GIT" || exit 1
 #
 #	Variables
 #
-	if [[ -z "$4" ]]
-	then	if [[ -d "$DIR_CFG/$1" ]]
+	if [ -z "$4" ]
+	then	if [ -d "$DIR_CFG/$1" ]
 		then	LBL="$1"
 		else	tui-echo "Please select the label to work with:"
 			select LBL in $(cd "$DIR_CFG";ls|grep -v \.);do break;done
@@ -41,15 +44,49 @@
 	else	LBL="$4"
 	fi
 	source "$DIR_CFG/$LBL/$LBL.conf"
+	tui-status $? "Selected project $prj_name ($LBL)"
 #
 #	Display & Action
 #
 	cd "$prj_path"
-	if [[ "" = "$(git status|grep -e del -e del)" ]]
-	then	git push origin master
+	LC_ALL=C ; export LC_ALL
+	
+	# Generate parsing string, and prepare parsing toggle
+	git_status="$(git status)"
+	mode=fail
+	
+	# Find reasons to make it pass
+	# Or should it be, find reasons to make it fail???
+	case "$git_status" in
+	*ahead*)	mode=pass	;;
+	esac
+	
+	# Add files? Delete leftovers? Commit changes? 
+	if [ fail = "$mode" ]
+	then	tui-status 1 "There are things to do..."
+		git status
+		tui-yesno "Handle with dev-scripts?" && \
+			ds prj git status $LBL || \
+			exit $?
+	fi
+	
+	tui-echo "Uploading data for $prj_name"
+	git push origin master
+	tui-status $? "Uploaded code of $prj_name"
+	ret=$?
+	cd "$oPWD"
+	exit $ret
+
+exit 0
+	if [ ! "" = "$(git status|grep ahead )" ]
+	then	tui-echo "Uploading data for $prj_name"
+		git push origin master
+		tui-status $? "Uploaded code of $prj_name"
 		cd "$oPWD"
 		exit $?
 	else	tui-status $? "There are uncommited changes"
 		git status
+		tui-yesno "Handle with dev-scripts?" && \
+			ds prj git status $LBL
 		exit $?
 	fi
diff --git a/menu/prj/mock/make b/menu/prj/mock/make
--- a/menu/prj/mock/make
+++ b/menu/prj/mock/make
@@ -25,7 +25,7 @@
 	source /etc/tui/commands.conf
 	source /etc/os-release
 	source /etc/tui/apps.conf #|| \
-	[[ 0 -ne $UID ]] || \
+	[ 0 -ne $UID ] || \
 		source $HOME/.config/tui/apps.conf
 	script_version=0.7.8
 	TOTAL_RET=0
@@ -57,7 +57,7 @@
 	done
 	shift $(($OPTIND - 1))
 	
-	if [[ -z "$4" ]] # || [[ ! -z "$LBL" ]]
+	if [ -z "$4" ] # || [[ ! -z "$LBL" ]]
 	then	if [[ -d "$DIR_CFG/$1" ]]
 		then	LBL="$1"
 		else	tui-echo "Please select the label to work with:"
@@ -68,7 +68,7 @@
 	
 	source "$CONF_RPM"
 	source "$DIR_CFG/$LBL/$LBL.conf"
-	if [[ -f "$DIR_CFG/$LBL/rpm.conf" ]]
+	if [ -f "$DIR_CFG/$LBL/rpm.conf" ]
 	then	source "$DIR_CFG/$LBL/rpm.conf"
 	else	tui-status 1 "Mock requires a specfile"
 		exit 1
@@ -107,7 +107,7 @@
 		dir_out="$FAS_REVIEW/$prj_name"
 		specfile=$dir_out/$prj_name.spec
 		tarball=$dir_out/$prj_name-$VER.$TAR_ET
-	else	[[ -z "$DIR_OUT" ]] && \
+	else	[ -z "$DIR_OUT" ] && \
 			dir_out="$HOME/data/out/$dist" && \
 			tui-conf-set \
 				$HOME/.config/dev-scripts/dev-scripts.conf \
@@ -122,8 +122,8 @@
 	# Was built by 'rpm'
 	# now looking for the latest...
 	[ -z "$TUI_TEMP_DIR" ] && exit 1
-	cd $dir_out && \
-		list=$prj_name*$VER*.src.rpm && \
+	cd "$dir_out" && \
+		list=$(find | $GREP -e $prj_name -e $VER | $GREP \.src\.rpm$) && \
 		for l in $list;do s="$l";done && \
 		SRC="$dir_out/$s"
 	tui-log $optVerb -t "$LOG" "Generated source rpm list (${#LIST[@]})"
@@ -144,8 +144,8 @@
 				if [ -f "/etc/mock/$T.cfg" ]
 				then	TASKS+=" $prj_name-$T"
 					echo "mock --target=$A -r $T $SRC 1>>$LOG_MOCK 2>>$LOG_MOCK " > "$TUI_TEMP_DIR/$prj_name-$T"
-					echo "[ 0 -eq \$? ] && msg=\"Successfully built\" || msg=\"Failed to build\"" >> "$TUI_TEMP_DIR/$prj_name-$T"
-					echo "tui-log -t \"$LOG\" \"\$msg $prj_name-$T\"" >> "$TUI_TEMP_DIR/$prj_name-$T"
+					#echo "[ 0 -eq \$? ] && msg=\"Successfully built\" || msg=\"Failed to build\"" >> "$TUI_TEMP_DIR/$prj_name-$T"
+					#echo "tui-log -t \"$LOG\" \"\$msg $prj_name-$T\"" >> "$TUI_TEMP_DIR/$prj_name-$T"
 					CHECK=$(($CHECK + 1))
 				else	tui-status 4 "Configuration for task \"$T\" does not exist."
 					TOTAL_SKIP=$(( $TOTAL_SKIP + 1 ))
@@ -179,7 +179,7 @@
 for T in $TASKS;do
 	cat $TUI_TEMP_DIR/\$T >> $LOG_MOCK
 	tui-bgjob "\$TUI_TEMP_DIR/\$T" "Packaging \$T" "Packaged \$T" && rm $TUI_TEMP_DIR/\$T
-	[[ 0 -ne \$? ]] && \\
+	[ 0 -ne \$? ] && \\
 			TOTAL_RET=$(( \$TOTAL_RET + 1 )) && \\
 			tui-filemgr /var/lib/mock/\$T/result
 	TOTAL_COUNT=$(( \$TOTAL_COUNT + 1 ))
@@ -224,7 +224,7 @@ EOF
 		for F in $LIST;do
 			tui-printf -rS 2 " * Moving: $(basename $F)"
 			#mv -f "$F" "$dir_out"
-			cp "$F" "$dir_out"
+			mv "$F" "$dir_out"
 			tui-status $? " * Moved: $(basename $F)" && \
 				msg="Successfully moved" || \
 				msg="Failed to move"
@@ -249,5 +249,5 @@ EOF
 	#else	tui-status $TOTAL_RET ""
 	fi
 	
-	[[ $TOTAL_RET -gt 0 ]] && RET=1  || RET=0
+	[ $TOTAL_RET -gt 0 ] && RET=1  || RET=0
 	exit $RET
